apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-location-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-location-app
  template:
    metadata:
      labels:
        app: cs-location-app
    spec:
      containers:
        - name: cs-location-app
          image: ishrakadit07/cs-location-app:latest
          ports:
            - containerPort: 8083
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cs-location-secrets
          key: POSTGRES_PASSWORD
