name: Dockerize & Deploy to AKS

on:
  # Uncomment when ready to trigger on push
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Build Spring Boot app
        run: |
          cd server
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cs-location-app:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cs-location-app:latest

      - name: Set up kubectl with base64 kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/kubeconfig.yaml
          echo "KUBECONFIG=$HOME/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
